/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Entity.Login;
import Entity.Mutexesisler;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Pallas
 */
public class ScreenLogin extends javax.swing.JFrame {

    private EntityManager em;
    private List<Mutexesisler> AllMutexesis;
    private final Login SingleLogin;
    private Login SingleLoginMutexesis;

    /**
     * Creates new form ScreenLogin
     */
    public ScreenLogin() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TexnoUSTA_ClientPU");
        em = emf.createEntityManager();
        AllMutexesis = em.createNamedQuery("Mutexesisler.findAll", Mutexesisler.class).getResultList();

        try (BufferedReader br = new BufferedReader(new FileReader("Login.txt"))) {

            String sCurrentLine;

            while ((sCurrentLine = br.readLine()) != null) {
                jComboBoxLogin.setSelectedIndex(Integer.parseInt(sCurrentLine));
                jComboBoxLogin.requestFocus();
                jComboBoxLogin.requestFocusInWindow();
            }

        } catch (IOException e) {
        }

        SingleLogin = em.createNamedQuery("Login.findByIdMutexesis", Login.class)
                .setParameter("idMutexesis", (jComboBoxLogin.getSelectedIndex() + 9))
                .getSingleResult();
        if (SingleLogin.getStatus().equals("1")) {
            jPassword.setText(SingleLogin.getPassword());
        }
    }

    public void login() throws FileNotFoundException, UnsupportedEncodingException {
        SingleLoginMutexesis = em.createNamedQuery("Login.findByIdMutexesis", Login.class)
                .setParameter("idMutexesis", (jComboBoxLogin.getSelectedIndex() + 9))
                .getSingleResult();
        if (SingleLoginMutexesis.getPassword().equals(jPassword.getText())) {
            if (jCheckBox1.isSelected()) {
                Login l = new Login(SingleLoginMutexesis.getIdLogin());
                l.setIdMutexesis(SingleLoginMutexesis.getIdMutexesis());
                l.setPassword(SingleLoginMutexesis.getPassword());
                l.setStatus("1");
                em.merge(l);
                em.getTransaction().begin();
                em.getTransaction().commit();
            } else {
                Login l = new Login(SingleLoginMutexesis.getIdLogin());
                l.setIdMutexesis(SingleLoginMutexesis.getIdMutexesis());
                l.setPassword(SingleLoginMutexesis.getPassword());
                l.setStatus("0");
                em.merge(l);
                em.getTransaction().begin();
                em.getTransaction().commit();
            }
            ScreenMain d = new ScreenMain(SingleLoginMutexesis);
            d.setVisible(true);

            try (PrintWriter writer = new PrintWriter("Login.txt", "UTF-8")) {
                writer.println((SingleLoginMutexesis.getIdMutexesis() - 9));
            }
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        TexnoUSTA_ClientPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TexnoUSTA_ClientPU").createEntityManager();
        mutexesislerQuery = java.beans.Beans.isDesignTime() ? null : TexnoUSTA_ClientPUEntityManager.createQuery("SELECT m FROM Mutexesisler m");
        mutexesislerList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mutexesislerQuery.getResultList();
        jButtonLogin = new javax.swing.JButton();
        jComboBoxLogin = new javax.swing.JComboBox<>();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogin.setText("Daxil ol");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jComboBoxLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mutexesislerList, jComboBoxLogin);
        bindingGroup.addBinding(jComboBoxBinding);

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Parol");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Məni xatırla dostum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxLogin, javax.swing.GroupLayout.Alignment.LEADING, 0, 216, Short.MAX_VALUE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButtonLogin))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
            //        NewClass d  = new NewClass();
            //        d.work();
            //
            login();
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(ScreenLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        try {
            login();
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(ScreenLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager TexnoUSTA_ClientPUEntityManager;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private java.util.List<Entity.Mutexesisler> mutexesislerList;
    private javax.persistence.Query mutexesislerQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
